# Final Project: Milestone 2
### Elizabeth Trunk, CMP 262
### April 15, 2026

In this project, I will analyze waterfalls in New Jersey.

### Set Up

In [1]:
import pandas as pd

In [2]:
df = "waterfalls.csv"
wf = pd.read_csv(df)

### Initial Exploratory Analysis

In [3]:
wf

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
0,1,27,Allamuchy Falls,NaN,Byram Twp.,Sussex,Cascade,,9.68,7.00,Public,"Located in Allamuchy Mountain State Park, this...",Trimble rangefinder,5/9/2019 12:00:00 AM,Jefferson Lake Tributary,426335.368,764606.933,bbbf0c68-16aa-4d81-8db9-976f1e3e905c,426335.367977,764606.932952
1,2,109,Apshawa Falls,NaN,West Milford Twp.,Passaic,Cascade,,8.50,8.50,Public,Located in Apshawa Preserve on Apshawa Creek. ...,Estimate,5/24/2023 12:00:00 AM,Apshawa Creek,524366.923,796009.519,f469f397-9cfc-4148-a768-f0ec8fc2cc12,524366.922898,796009.519097
2,3,118,Bear Swamp Brook Falls Lower,NaN,Mahwah Twp.,Bergen,Cascade,,15.00,15.00,Public,This falls slides over a big rounded ledge of ...,Literature search,5/25/2023 12:00:00 AM,Bear Swamp Brook,569200.226,817439.079,c49b73cb-3293-453f-88c3-b04da0ff5698,569200.225948,817439.078928
3,4,117,Bear Swamp Brook Falls Upper,NaN,Mahwah Twp.,Bergen,Cascade,,12.00,12.00,Public,"The falls are up Bear Swamp Road, a private ro...",Literature search,5/25/2023 12:00:00 AM,Bear Swamp Brook,568961.724,817709.178,7b7f8a6a-fea4-40c0-91b5-bf6a5560d1c4,568961.724128,817709.178125
4,5,108,Bear Swamp Brook Unnamed Falls,NaN,Mahwah Twp.,Bergen,Cascade,,5.30,5.30,Public,"The falls are up Bear Swamp Road, a private ro...",Trimble rangefinder,5/25/2023 12:00:00 AM,Bear Swamp Brook,569465.790,817181.169,86b3ee23-1f31-4d85-a28e-2ba6e3b12f62,569465.790049,817181.169011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114,99,Van Campens Glen Unnamed Waterfall 2,NaN,Hardwick Twp.,Warren,Plunge,,11.00,11.00,Public,A small waterfall a few hundred feet upstream ...,Trimble rangefinder,6/25/2019 12:00:00 AM,Vancampens Brook,357357.892,812291.224,6add5441-80d1-4048-b009-d0d87a08b9e8,357357.892087,812291.224066
114,115,24,Wanaque River Falls,NaN,West Milford Twp.,Passaic,Chute,,7.15,7.15,Public,Small waterfall located on the Wanaque River a...,Trimble rangefinder,4/14/2022 12:00:00 AM,Wanaque River,542914.892,848610.479,03221fce-47bc-45f5-95fc-8bae87889a9c,542914.892035,848610.478855
115,116,98,Weldon Quarry Falls,NaN,Hopatcong Borough,Sussex,Cascade,,10.20,4.00,Private,A small cascade next to the Weldon Quarry on p...,Trimble rangefinder,11/20/2019 12:00:00 AM,Weldon Brook Tributary,458973.640,785094.430,2d124c38-199e-4529-adbe-3d46d8e5516e,458973.639971,785094.430035
116,117,100,Wetumpka Falls,NaN,Watchung Borough,Union,Cascade,,20.00,9.00,Public,Located along Somers Ave. on Stony Brook acros...,Trimble rangefinder,9/13/2017 12:00:00 AM,Stony Brook,506789.027,655884.180,7c7b98ee-1455-4854-b30d-6aa1c215393c,506789.026951,655884.179925
117,118,25,Wyanokie Falls,NaN,Bloomingdale Borough,Passaic,Multi-step waterfall,Cascade,31.50,15.00,Public,Two tier falls located along Blue Mine Brook. ...,Trimble rangefinder,9/13/2017 12:00:00 AM,Blue Mine Brook,541848.548,812984.077,a2078aa6-ee1d-4972-8baf-b6fdc317ae6a,541848.548039,812984.077011

In [4]:
wf.describe()

,OBJECTID,ID,Approximate Height (ft),Approximate Height 2 (ft),NJSPC83 Easting (X),NJSPC83 Northing (Y),x,y
count,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000
mean,59.500000,59.500000,20.664153,15.133305,454957.450569,766787.691911,454954.599897,766786.520829
std,34.207699,34.207699,31.807566,13.876153,103181.535758,77134.500108,103176.040255,77134.156539
min,1.000000,1.000000,1.000000,1.000000,317784.388000,503398.555000,317784.387901,503398.555107
25%,30.250000,30.250000,7.000000,6.000000,357433.350250,718739.527250,357433.350352,718739.527147
50%,59.500000,59.500000,12.300000,11.950000,429578.302000,789190.000000,429578.302108,789157.271154
75%,88.750000,88.750000,21.350000,18.000000,541390.147000,815008.556250,541390.147053,815008.556230
max,118.000000,118.000000,250.000000,85.000000,652330.000000,892620.707000,652240.180930,892620.707108

In [5]:
wf.columns

Index(['OBJECTID', 'ID', 'Waterfall Name', 'Alternate Name', 'Municipality',
       'County', 'Waterfall Type 1', 'Waterfall Type 2',
       'Approximate Height (ft)', 'Approximate Height 2 (ft)', 'Access',
       'Comments', 'Measurement', 'Date Measured', 'Stream Name',
       'NJSPC83 Easting (X)', 'NJSPC83 Northing (Y)', 'GlobalID', 'x', 'y'],
      dtype='object')

In [6]:
wf.shape

(118, 20)

In [7]:
wf.dtypes

OBJECTID                       int64
ID                             int64
Waterfall Name                object
Alternate Name                object
Municipality                  object
County                        object
Waterfall Type 1              object
Waterfall Type 2              object
Approximate Height (ft)      float64
Approximate Height 2 (ft)    float64
Access                        object
Comments                      object
Measurement                   object
Date Measured                 object
Stream Name                   object
NJSPC83 Easting (X)          float64
NJSPC83 Northing (Y)         float64
GlobalID                      object
x                            float64
y                            float64
dtype: object

In [8]:
wf.head()

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
0,1,27,Allamuchy Falls,NaN,Byram Twp.,Sussex,Cascade,,9.68,7.0,Public,"Located in Allamuchy Mountain State Park, this...",Trimble rangefinder,5/9/2019 12:00:00 AM,Jefferson Lake Tributary,426335.368,764606.933,bbbf0c68-16aa-4d81-8db9-976f1e3e905c,426335.367977,764606.932952
1,2,109,Apshawa Falls,NaN,West Milford Twp.,Passaic,Cascade,,8.50,8.5,Public,Located in Apshawa Preserve on Apshawa Creek. ...,Estimate,5/24/2023 12:00:00 AM,Apshawa Creek,524366.923,796009.519,f469f397-9cfc-4148-a768-f0ec8fc2cc12,524366.922898,796009.519097
2,3,118,Bear Swamp Brook Falls Lower,NaN,Mahwah Twp.,Bergen,Cascade,,15.00,15.0,Public,This falls slides over a big rounded ledge of ...,Literature search,5/25/2023 12:00:00 AM,Bear Swamp Brook,569200.226,817439.079,c49b73cb-3293-453f-88c3-b04da0ff5698,569200.225948,817439.078928
3,4,117,Bear Swamp Brook Falls Upper,NaN,Mahwah Twp.,Bergen,Cascade,,12.00,12.0,Public,"The falls are up Bear Swamp Road, a private ro...",Literature search,5/25/2023 12:00:00 AM,Bear Swamp Brook,568961.724,817709.178,7b7f8a6a-fea4-40c0-91b5-bf6a5560d1c4,568961.724128,817709.178125
4,5,108,Bear Swamp Brook Unnamed Falls,NaN,Mahwah Twp.,Bergen,Cascade,,5.30,5.3,Public,"The falls are up Bear Swamp Road, a private ro...",Trimble rangefinder,5/25/2023 12:00:00 AM,Bear Swamp Brook,569465.790,817181.169,86b3ee23-1f31-4d85-a28e-2ba6e3b12f62,569465.790049,817181.169011

In [9]:
wf.tail()

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
113,114,99,Van Campens Glen Unnamed Waterfall 2,NaN,Hardwick Twp.,Warren,Plunge,,11.00,11.00,Public,A small waterfall a few hundred feet upstream ...,Trimble rangefinder,6/25/2019 12:00:00 AM,Vancampens Brook,357357.892,812291.224,6add5441-80d1-4048-b009-d0d87a08b9e8,357357.892087,812291.224066
114,115,24,Wanaque River Falls,NaN,West Milford Twp.,Passaic,Chute,,7.15,7.15,Public,Small waterfall located on the Wanaque River a...,Trimble rangefinder,4/14/2022 12:00:00 AM,Wanaque River,542914.892,848610.479,03221fce-47bc-45f5-95fc-8bae87889a9c,542914.892035,848610.478855
115,116,98,Weldon Quarry Falls,NaN,Hopatcong Borough,Sussex,Cascade,,10.20,4.00,Private,A small cascade next to the Weldon Quarry on p...,Trimble rangefinder,11/20/2019 12:00:00 AM,Weldon Brook Tributary,458973.640,785094.430,2d124c38-199e-4529-adbe-3d46d8e5516e,458973.639971,785094.430035
116,117,100,Wetumpka Falls,NaN,Watchung Borough,Union,Cascade,,20.00,9.00,Public,Located along Somers Ave. on Stony Brook acros...,Trimble rangefinder,9/13/2017 12:00:00 AM,Stony Brook,506789.027,655884.180,7c7b98ee-1455-4854-b30d-6aa1c215393c,506789.026951,655884.179925
117,118,25,Wyanokie Falls,NaN,Bloomingdale Borough,Passaic,Multi-step waterfall,Cascade,31.50,15.00,Public,Two tier falls located along Blue Mine Brook. ...,Trimble rangefinder,9/13/2017 12:00:00 AM,Blue Mine Brook,541848.548,812984.077,a2078aa6-ee1d-4972-8baf-b6fdc317ae6a,541848.548039,812984.077011

In [10]:
wf.sample(5)

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
21,22,41,Clinton Falls (High Falls),"High Falls, Janetta Falls",West Milford Twp.,Passaic,Plunge,Chute,20.0,20.0,Public,The falls is located under a stone bridge on C...,Trimble rangefinder,3/14/2019 12:00:00 AM,Clinton Brook,505897.479,815432.175,4abf0189-12ea-4801-ac03-3278091f1ee2,505897.478866,815432.175133
42,43,83,Flat Brook Tributary Unnamed Waterfall 3,NaN,Walpack Twp.,Sussex,Cascade,,4.0,4.0,Public,Small waterfall on west side of Kittattinny Mo...,Estimate,6/7/2023 12:00:00 AM,Flat Brook Tributary,379689.652,832340.396,e1f806eb-dd3f-41a9-8256-262dc999381e,379689.651885,832340.395910
104,105,19,Tumble Falls 3,NaN,Kingwood Twp.,Hunterdon,Cascade,,30.0,30.0,Private,Located along Rt. 29. Located 200 feet back fr...,Estimate,9/27/2018 12:00:00 AM,Delaware River Tributary,335427.610,586611.410,646f14e8-e9c1-41f7-9301-457ea78fb173,335427.610160,586611.410007
18,19,38,Cataract Falls,The Cataract,Washington Twp.,Morris,Cataract,Cascade,51.5,44.3,Public,The top section of the falls is very tall. Loc...,Trimble rangefinder,3/20/2019 12:00:00 AM,Schooleys Mountain Brook Tributary,405452.434,721653.824,b5134987-cf98-44b7-9caf-f60ddc7b239a,405452.434021,721653.823976
43,44,84,Flat Brook Tributary Unnamed Waterfall 4,NaN,Walpack Twp.,Sussex,Cascade,,4.0,4.0,Public,Small waterfall on west side of Kittattinny Mo...,Estimate,6/7/2023 12:00:00 AM,Flat Brook Tributary,379429.991,832653.125,036f3b4e-cf7b-4c9f-a1a3-1af1750a0445,379429.990987,832653.124943

In [11]:
wf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OBJECTID                   118 non-null    int64
 1   ID                         118 non-null    int64
 2   Waterfall Name             118 non-null    object
 3   Alternate Name             16 non-null     object
 4   Municipality               118 non-null    object
 5   County                     118 non-null    object
 6   Waterfall Type 1           118 non-null    object
 7   Waterfall Type 2           114 non-null    object
 8   Approximate Height (ft)    118 non-null    float64
 9   Approximate Height 2 (ft)  118 non-null    float64
 10  Access                     118 non-null    object
 11  Comments                   118 non-null    object
 12  Measurement                118 non-null    object
 13  Date Measured              118 non-null    object
 14  Stream Name                118 non-null    object
 15  NJSPC83 Easting (X)        118 non-null    float64
 16  NJSPC83 Northing (Y)       118 non-null    float64
 17  GlobalID                   118 non-null    object
 18  x                          118 non-null    float64
 19  y                          118 non-null    float64
dtypes: float64(6), int64(2), object(12)
memory usage: 18.6+ KB

In [12]:
wf.sort_values('Approximate Height (ft)', ascending = False)

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
45,46,89,Greenbrook Falls,NaN,Alpine Borough,Bergen,Plunge,Cascade,250.00,85.00,Public,The estimated 250-foot Greenbrook Falls is New...,Literature search,5/3/2018 12:00:00 AM,Green Brook,650098.647,760552.154,30d91fd4-9799-4f6b-ba34-31e2cfe94b47,650098.647156,760552.153988
62,63,91,Lost Brook Falls,NaN,Tenafly Borough,Bergen,Cascade,,200.00,75.00,Public,Second largest falls in New Jersey. It cascade...,Estimate,5/3/2018 12:00:00 AM,Lost Brook,648938.790,757636.782,35416096-aee8-4e94-914e-e6fdba7f9f88,648938.789895,757636.781866
13,14,33,Buttermilk Falls,NaN,Walpack Twp.,Sussex,Multi-step waterfall,Cascade,130.00,30.00,Public,The third tallest waterfall in NJ.,Trimble rangefinder,7/26/2017 12:00:00 AM,Flat Brook Tributary,384958.815,839348.272,abf6cbe5-b13d-44bd-bb1d-a18d49eea72d,384958.814904,839348.271986
44,45,85,Great Falls of the Passaic,"Totowa Falls, Great Falls",Paterson,Passaic,Block Waterfall,NaN,77.00,77.00,Public,Small waterfall on west side of Kittattinny Mo...,Literature search,8/5/2017 12:00:00 AM,Passaic River,580237.919,758669.410,4b355710-705f-4eaf-bbff-6343e3cb0afe,580237.919095,758669.410050
66,67,92,Old Mine Road Unnamed Waterfall 1,NaN,Hardwick Twp.,Sussex,Cascade,Multi-step waterfall,60.90,17.70,Public,Located along Old Mine Road. A multi-tiered st...,Trimble rangefinder,3/28/2019 12:00:00 AM,Delaware River Tributary,326967.038,791392.512,4e30cb4e-95de-4dc2-bef6-ae534a07c472,326967.037843,791392.511927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,39,52,Dunnfield Creek Natural Area Unnamed Waterfall 8,NaN,Hardwick Twp.,Warren,Cascade,,3.79,3.79,Public,Small cascade with unknown name at the junctio...,Estimate,10/30/2019 12:00:00 AM,Dunnfield Creek,320063.000,780956.000,b61deb38-924c-4e70-b2f2-5ea02628fc4a,320063.000142,780955.999991
75,76,74,Rinehart Brook Falls Lower,NaN,Chester Twp.,Morris,Cascade,,3.71,3.71,Public,Small falls on Rinehart Brook.,Trimble rangefinder,7/30/2019 12:00:00 AM,Rinehart Brook,427924.405,696095.976,99cf32d7-1716-44e6-8e08-84c04d35803a,427924.405153,696095.976142
58,59,63,Little Falls 2,NaN,Little Falls,Passaic,Cascade,,2.00,2.00,Public,Downstream of the Little Falls closest to the ...,Trimble rangefinder,7/11/2019 12:00:00 AM,Passaic River Tributary,566023.792,746895.822,020571ba-39b9-4a33-b06b-54773d9e92ef,566023.792012,746895.822049
59,60,64,Little Falls 3,NaN,Little Falls,Passaic,Cascade,,1.32,1.32,Public,Downstream of the Little Falls closest to the ...,Trimble rangefinder,7/11/2019 12:00:00 AM,Passaic River Tributary,566151.223,746818.238,397313c7-33d4-44b7-b337-92ce91397b62,566151.222859,746818.237886
100,101,15,Trenton Falls,Falls of the Delaware,Trenton,Mercer,Cascade,,1.00,1.00,Public,GPS location taken from PA side of Delaware. N...,Literature search,7/12/2017 12:00:00 AM,Delaware River,415866.814,503398.555,21f19c70-318e-45b7-9dea-cc6fef0474e9,415866.814111,503398.555107

In [13]:
wf[wf['Waterfall Type 1' or 'Waterfall Type 2'] == 'Horsetail']

,OBJECTID,ID,Waterfall Name,Alternate Name,Municipality,County,Waterfall Type 1,Waterfall Type 2,Approximate Height (ft),Approximate Height 2 (ft),Access,Comments,Measurement,Date Measured,Stream Name,NJSPC83 Easting (X),NJSPC83 Northing (Y),GlobalID,x,y
15,16,35,Buttermilk Falls,NaN,Bridgewater Twp.,Somerset,Horsetail,,27.2,27.2,Public,Located in Washington Valley Park. At the end ...,Trimble rangefinder,3/14/2019 12:00:00 AM,MacMillan Brook,476263.477,638324.458,d84d1f7c-b771-416c-9d0b-2789e92ffef6,476263.47711,638324.458155

In [14]:
wf['Waterfall Type 1' or 'Waterfall Type 2'].unique()

array(['Cascade', 'Multi-step waterfall', 'Plunge', 'Horsetail',
       'Cataract', 'Fantail', 'Chute', 'Block Waterfall'], dtype=object)

In [15]:
wf['Waterfall Type 1' or 'Waterfall Type 2'].value_counts()

Cascade                 93
Multi-step waterfall     8
Chute                    7
Plunge                   4
Cataract                 2
Fantail                  2
Horsetail                1
Block Waterfall          1
Name: Waterfall Type 1, dtype: int64

In [16]:
wf_morris = wf[wf['County'] == 'Morris']
wf_morris['Municipality'].value_counts()

Chester Twp.       8
Washington Twp.    7
Mendham Twp.       2
Boonton            1
Mine Hill Twp.     1
Montville Twp.     1
Name: Municipality, dtype: int64